In [2]:
import numpy as np

In [15]:
from darm_gym_env import DARMEnv

env = DARMEnv(render_mode=None, 
                action_time=0.08, 
                hand_name="hand1", 
                digits=["i", "ii", "iii", "iv", "v"], 
                ignore_load_start_states=True)

Loaded XML file successfully
Using step size `0.01256` units
Using `myo` reward type
Number of tendon position actuators: 30
Using `Box([-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.], (30,), float32)` action space


/home/daniel/miniconda3/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [26]:
M0 = env.data.body('hand1_mcp_centre_block_iii').xpos
env.transform_distance_obs(M0)/100

array([0.0082, 0.0087, 0.0933])

In [38]:
darm_orient = np.array([env.get_fingertip_pose(i)[3:7] for i in ["ii", "iii", "iv", "v"]])
darm_orient

array([[ 0.9952465415, -0.0038016801,  0.0434534024, -0.0870727898],
       [ 1.0000000000,  0.0000000000,  0.0000000000,  0.0000000000],
       [ 0.9980973490, -0.0019026510, -0.0435778714,  0.0435778714],
       [ 0.9935753309, -0.0045594675, -0.1044289753,  0.0433804358]])

In [43]:
np.roll(darm_orient, shift=1, axis=-1)

array([[-0.0870727898,  0.9952465415, -0.0038016801,  0.0434534024],
       [ 0.0000000000,  1.0000000000,  0.0000000000,  0.0000000000],
       [ 0.0435778714,  0.9980973490, -0.0019026510, -0.0435778714],
       [ 0.0433804358,  0.9935753309, -0.0045594675, -0.1044289753]])

In [49]:
cam_orientations = np.array([[ 0.50,  0.44, -0.62, -0.41],
 [ 0.48,  0.41, -0.63, -0.45],
 [ 0.51,  0.37, -0.61, -0.48],
 [ 0.55,  0.41, -0.49, -0.54]])


# [[ 0.47  0.45 -0.62 -0.44]
#  [ 0.47  0.44 -0.60 -0.47]
#  [ 0.49  0.40 -0.59 -0.50]
#  [ 0.53  0.42 -0.49 -0.55]]
# [[ 0.44  0.46 -0.62 -0.46]
#  [ 0.46  0.43 -0.61 -0.48]
#  [ 0.49  0.40 -0.60 -0.50]
#  [ 0.51  0.43 -0.42 -0.61]]


In [79]:
obs = cam_orientations
w = obs[:, 3].copy()
xzy = obs[:, 0:3].copy()

obs[:, 3] = np.cos(w/2)
obs[:, 0:3] = xzy*np.reshape(np.sin(w/2), (4, 1))
# xzy, np.reshape(np.sin(w/2), (4, 1))
w, xzy, obs

(array([0.9003672226, 0.9003672226, 0.9003672226, 0.9003672226]),
 array([[ 0.0000003593,  0.0000003162, -0.0000004456],
        [ 0.0000003450,  0.0000002947, -0.0000004528],
        [ 0.0000003665,  0.0000002659, -0.0000004384],
        [ 0.0000003953,  0.0000002947, -0.0000003522]]),
 array([[ 0.0000001564,  0.0000001376, -0.0000001939,  0.9003672226],
        [ 0.0000001501,  0.0000001282, -0.0000001970,  0.9003672226],
        [ 0.0000001595,  0.0000001157, -0.0000001908,  0.9003672226],
        [ 0.0000001720,  0.0000001282, -0.0000001532,  0.9003672226]]))

In [ ]:
cam_fingertips = [[ 3.87,  0.79, 18.35],
 [ 0.23,  1.26, 19.74],
 [-3.31,  1.91, 18.80],
 [-7.67, -2.75, 14.81]]

# Updated IK_REF_LENGTH
[[ 2.47 -1.33 19.06]
 [-2.16  0.02 20.26]
 [-4.97 -0.87 18.35]
 [-8.94 -3.19 14.01]]


# [[ 2.80,  2.33 18.51]
#  [-0.87  2.80 19.92]
#  [-4.22  2.42 19.15]
#  [-8.39 -1.88 15.10]]
# [[ 3.69  0.76 18.49]
#  [-0.24  0.10 20.22]
#  [-3.61  0.76 19.25]
#  [-7.68 -3.19 14.93]]
# [[ 4.18  0.40 18.04]
#  [ 0.28  1.00 20.03]
#  [-3.12  0.53 19.14]
#  [-7.24 -3.70 14.88]]


In [3]:
xyz = np.array(
 [[-3.39925997e-02,  9.87073302e-01, -2.79414654e-02],
 [-3.61008495e-01,  6.91357076e-01, -1.35344356e-01],
 [-5.48815846e-01,  4.44738656e-01, -3.01499397e-01],
 [-7.51019418e-01,  1.47613123e-01, -4.16701674e-01],
 [-8.93601775e-01, -2.90188968e-01, -5.27223885e-01],
 [-2.67713130e-01,  4.11484763e-03,  4.41602878e-02],
 [-3.93326938e-01, -4.32319582e-01,  1.75442636e-01],
 [-4.40349638e-01, -7.16268122e-01,  1.04264364e-01],
 [-4.36610579e-01, -1.06917846e+00,  7.08148777e-02],
 [-1.03901687e-09, -1.94015914e-11,  1.36727474e-09],
 [-4.62662466e-02, -4.40103680e-01,  1.48882017e-01],
 [-5.72443567e-02, -8.40861678e-01,  1.26788393e-01],
 [-1.20948255e-03, -1.19423902e+00,  4.61350456e-02],
 [ 1.99696794e-01,  8.16008896e-02, -1.23154104e-01],
 [ 2.21037939e-01, -3.29691291e-01,  1.63794458e-02],
 [ 2.68396527e-01, -6.33840919e-01, -3.40695269e-02],
 [ 2.85621703e-01, -1.05759454e+00, -7.90690780e-02],
 [ 3.37258935e-01,  2.30879441e-01, -3.25287253e-01],
 [ 4.82951164e-01, -1.74280286e-01, -3.87838960e-01],
 [ 4.77099478e-01, -3.34338069e-01, -4.37369615e-01],
 [ 5.50493598e-01, -6.50341213e-01, -4.79206741e-01]]
)
xyz.shape

(21, 3)

In [25]:
np.set_printoptions(precision=10, suppress=True, floatmode="maxprec_equal", )

In [5]:
# [X, Z, Y]
# +X points towrads the little finger
# +Z points towards wrist
# +Y points dorsally
# Ref M0, index 9

IK_UNIT_LENGTH = 0.09473151311686484 # in meter
scale = IK_UNIT_LENGTH*100

# WRIST
xyz[0]*scale

array([-0.32,  9.35, -0.26])

In [6]:
def trf(a):
    IK_UNIT_LENGTH = 0.09473151311686484 # in meter
    scale = IK_UNIT_LENGTH*100

    res = (a - xyz[0])*scale*[-1, -1, 1]
    
    z = res[:, 1].copy()
    y = res[:, 2].copy()
    res[:,1] = y
    res[:, 2] = z
    
    return res

In [22]:
trf(xyz[9:13])

array([[-0.32,  0.26,  9.35],
       [ 0.12,  1.68, 13.52],
       [ 0.22,  1.47, 17.32],
       [-0.31,  0.70, 20.66]])

In [21]:
a = xyz[9:13] - xyz[0]
a=a*scale
a = a*[-1, -1, 1]
a

array([[-0.32,  9.35,  0.26],
       [ 0.12, 13.52,  1.68],
       [ 0.22, 17.32,  1.47],
       [-0.31, 20.66,  0.70]])

In [19]:
z = a[:, 1].copy()
y = a[:, 2].copy()
a[:,1] = y; a[:, 2] = z
a

array([[-0.32,  0.26,  9.35],
       [ 0.12,  1.68, 13.52],
       [ 0.22,  1.47, 17.32],
       [-0.31,  0.70, 20.66]])

In [9]:
# MIDDLE FINGER
xyz[9]*scale, xyz[10]*scale, xyz[11]*scale, xyz[12]*scale

(array([-0., -0.,  0.]),
 array([-0.44, -4.17,  1.41]),
 array([-0.54, -7.97,  1.20]),
 array([ -0.01, -11.31,   0.44]))

In [50]:
# INDEX FINGER
xyz[5]*scale, xyz[6]*scale, xyz[7]*scale, xyz[8]*scale

(array([-2.54,  0.04,  0.42]),
 array([-3.73, -4.10,  1.66]),
 array([-4.17, -6.79,  0.99]),
 array([ -4.14, -10.13,   0.67]))

In [26]:
print(xyz)

[[-0.034  0.987 -0.028]
 [-0.361  0.691 -0.135]
 [-0.549  0.445 -0.301]
 [-0.751  0.148 -0.417]
 [-0.894 -0.290 -0.527]
 [-0.268  0.004  0.044]
 [-0.393 -0.432  0.175]
 [-0.440 -0.716  0.104]
 [-0.437 -1.069  0.071]
 [-0.000 -0.000  0.000]
 [-0.046 -0.440  0.149]
 [-0.057 -0.841  0.127]
 [-0.001 -1.194  0.046]
 [ 0.200  0.082 -0.123]
 [ 0.221 -0.330  0.016]
 [ 0.268 -0.634 -0.034]
 [ 0.286 -1.058 -0.079]
 [ 0.337  0.231 -0.325]
 [ 0.483 -0.174 -0.388]
 [ 0.477 -0.334 -0.437]
 [ 0.550 -0.650 -0.479]]
